#!/bin/bash
# Helper script for Dropbox authentication

echo "🔐 Dropbox Authentication Setup"
echo "==============================="
echo ""
echo "Step 1: Open this URL in your browser:"
echo "https://www.dropbox.com/1/oauth2/authorize?client_id=07o23gulcj8qi69&response_type=code&state=state"
echo ""
echo "Step 2: Click 'Allow' (log in to Dropbox if needed)"
echo ""
echo "Step 3: Copy the authorization code from the page"
echo ""
echo "Step 4: Run: dbxcli account"
echo "        Then paste the code when prompted"
echo ""
echo "Step 5: Test with: dbxcli ls /"
echo ""
echo "After authentication, create HRM folders:"
echo "  dbxcli mkdir /HRM"
echo "  dbxcli mkdir /HRM/checkpoints"
echo "  dbxcli mkdir /HRM/datasets"
echo "  dbxcli mkdir /HRM/logs"
echo "  dbxcli mkdir /HRM/configs"
echo ""
echo "Or run: ./setup_folders.sh"